
project_id = "bjpawnertrqwtgyvrhml"

[db.wrangler]
nodes = 1
database_id = "db"
local_port = 54322

[[edge_functions]]
name = "generate-segments-structure"

[[edge_functions]]
name = "generate-segment-content"

[[edge_functions]]
name = "extract-pdf-text"

[[edge_functions]]
name = "chat-with-lecture"

[[edge_functions]]
name = "generate-flashcards"

[[edge_functions]]
name = "generate-lecture-summary"

[[edge_functions]]
name = "generate-mindmap"

[[edge_functions]]
name = "generate-quiz"

[[edge_functions]]
name = "generate-resources"

[[edge_functions]]
name = "generate-story-content"

[[edge_functions]]
name = "map-subject-content"
