project_id = "bjpawnertrqwtgyvrhml"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.extract-pdf-text]
verify_jwt = false

[functions.generate-lecture-summary]
verify_jwt = false

[functions.generate-mindmap]
verify_jwt = false

[functions.generate-resources]
verify_jwt = false

[functions.generate-story-content]
verify_jwt = false