
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjpawnertrqwtgyvrhml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcGF3bmVydHJxd3RneXZyaG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDc3MDksImV4cCI6MjA1MzkyMzcwOX0.KpxUdrQwYWCV0n2akKhjbkmirKyid41kHw322gB3FV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if a storage bucket exists and create it if it doesn't
export const ensureBucketExists = async (bucketName: string) => {
  try {
    // Try to get the bucket first
    const { data: bucket, error } = await supabase.storage.getBucket(bucketName);
    
    if (error) {
      console.log(`Bucket ${bucketName} doesn't exist, creating it...`);
      const { data, error: createError } = await supabase.storage.createBucket(bucketName, {
        public: true,
        fileSizeLimit: 50 * 1024 * 1024, // 50MB limit for podcast files
      });
      
      if (createError) {
        console.error(`Error creating ${bucketName} bucket:`, createError);
        return false;
      }
      console.log(`Successfully created ${bucketName} bucket`);
      return true;
    }
    
    console.log(`Bucket ${bucketName} already exists`);
    return true;
  } catch (error) {
    console.error('Error checking/creating bucket:', error);
    return false;
  }
};
